language: android
android:
  components:
    - tools
    - platform-tools
    - tools

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-26
    - sys-img-armeabi-v7a-android-17
before_script:
  - chmod +x gradlew
